"""empty message

Revision ID: 9bfc743949e6
Revises: 1d8a7bfe707c
Create Date: 2020-05-10 13:29:46.882538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfc743949e6'
down_revision = '1d8a7bfe707c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('posted_on', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date_posted')
    op.drop_column('blog', 'posted_on')
    # ### end Alembic commands ###
